# Generated by Django 5.2.4 on 2025-07-11 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 17, 27, 42, 953822, tzinfo=datetime.timezone.utc)),
        ),
    ]
