# Generated by Django 5.2.4 on 2025-07-11 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 11, 17, 48, 35, 878543, tzinfo=datetime.timezone.utc)),
        ),
    ]
