# Generated by Django 5.2.4 on 2025-07-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(max_length=350, verbose_name='short description')),
                ('price_main', models.PositiveIntegerField(verbose_name='price main')),
                ('price_discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='price discount')),
                ('image', models.ImageField(upload_to='foods/', verbose_name='image')),
                ('inventory', models.IntegerField(default=1, verbose_name='inventory')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='shop.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'food',
                'verbose_name_plural': 'foods',
                'ordering': ['-created_at'],
            },
        ),
    ]
